system: part1a.c
	gcc -D SYSTEM part1a.c -o tshell

fork:	part1b.c
	gcc -D FORK part1b.c -o tshell

vfork:	part1c.c
	gcc -D VFORK part1c.c -o tshell

clone:	part1d.c
	gcc -D CLONE part1d.c -o tshell

pipe-writer:	part1e-input.c
		gcc -D PIPEWRITER part1e-input.c -o tshell

pipe-reader:	part1e-output.c
		gcc -D PIPEREADER part1e-output.c -o tshell


